baseurl = "/"
productionurl = "https://avaruuskerho.fi/"
languageCode = "en-us"
languageLang = "en"
title = "Castor"

[menu]
    [[menu.nav]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 1
    [[menu.nav]]
        identifier = "club-room"
        name = "Club Room"
        url = "/club-room"
        weight = 2
    [[menu.nav]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 3
    [[menu.nav]]
         identifier = "join"
         name = "Join!"
         url = "/join"
         weight = 4

[markup.goldmark.renderer]
  unsafe=true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
